#!/usr/bin/env python3
"""Render the dossier's bibliography section (§7) from papers.yaml.

papers.yaml is the single source of truth. Edit it, run this script, commit both
files. Everything in dossier.md from the §7 heading onward is overwritten.
"""
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parent
DOSSIER = ROOT / "dossier.md"

MISSING = "—"
LOSSLESS = {True: "✓", False: "✗", "~": "~"}
COLUMNS = ["Paper", "Summary", "Lossless", "Max ctx", "Acceptance", "Speedup", "Long-ctx note"]
GENERATED = "<!-- GENERATED by build.py from papers.yaml — edit those, not this section. -->"
HEADING = "## 7. 📚 ANNOTATED BIBLIOGRAPHY: THE LANDSCAPE BY METHOD FAMILY"


def cell(value):
    if value in (None, ""):
        return MISSING
    return str(value).replace("|", "\\|").replace("\n", " ")


def paper_cell(p):
    url = p.get("url") or (f"https://arxiv.org/abs/{p['arxiv']}" if p.get("arxiv") else None)
    label = f"[{p['name']}]({url})" if url else f"**{p['name']}**"
    return f"{label} '{str(p['year'])[-2:]}" if p.get("year") else label


def anchor(title):
    slug = re.sub(r"[^\w\s-]", "", title.lower())
    return re.sub(r"\s+", "-", slug.strip())


def family_table(papers):
    lines = ["| " + " | ".join(COLUMNS) + " |", "|" + "---|" * len(COLUMNS)]
    for p in papers:
        row = [
            paper_cell(p),
            cell(p.get("summary")),
            LOSSLESS.get(p.get("lossless"), MISSING),
            cell(p.get("max_ctx")),
            cell(p.get("acceptance")),
            cell(p.get("speedup")),
            cell(p.get("note")),
        ]
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def index_table(families, by_family):
    lines = ["| Family | Verdict | Papers |", "|---|---|---|"]
    for f in families:
        name = f"[{f['name']}](#{anchor(f['name'])})"
        lines.append(f"| {name} | {f['verdict']} | {len(by_family.get(f['key'], []))} |")
    return "\n".join(lines)


def main():
    data = yaml.safe_load((ROOT / "papers.yaml").read_text())
    families, papers = data["families"], data["papers"]

    known = {f["key"] for f in families}
    by_family = {}
    for p in papers:
        if p["family"] not in known:
            sys.exit(f"error: unknown family '{p['family']}' for paper '{p['name']}'")
        if not p.get("url") and not p.get("arxiv"):
            print(f"warning: no link for '{p['name']}'")
        by_family.setdefault(p["family"], []).append(p)

    parts = [HEADING, "", GENERATED, "", data["preamble"].strip(), "",
             index_table(families, by_family), ""]
    for f in families:
        parts += [f"### {f['name']}", "", f"**Verdict: {f['verdict']}**", "",
                  family_table(by_family.get(f["key"], [])), ""]

    text = DOSSIER.read_text()
    pos = text.find("## 7. ")
    if pos == -1:
        sys.exit("error: bibliography heading not found in dossier.md")
    DOSSIER.write_text(text[:pos] + "\n".join(parts).rstrip() + "\n")

    print(f"{len(papers)} papers, {len(families)} families -> dossier.md §7")


if __name__ == "__main__":
    main()
